version: "3.8"

services:
  postgres:
    container_name: next_postgres
    image: postgres
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=presensi_db
    ports:
      - 5432:5432